### ISSUE TITLE
FE is broken

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/FastBTC#21]
`http://localhost:3007/socket.io/?EIO=3&transport=polling&xxx` returns Bad Request 

![image](https://user-images.githubusercontent.com/40721795/109515006-e4fedd80-7aa6-11eb-8c14-bade8b6d87c4.png)

**Comment by Bitcoinera** [comment]
Maybe it is only on my side? Very strange

**Comment by jamiemadrox779** [comment]
done
