### ISSUE TITLE
Telegram bot on bitcoinCtrl does not work

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/FastBTC#23]
(node:16803) UnhandledPromiseRejectionWarning: Error: 404: Not Found
    at /home/ubuntu/FastBtc/FastBTC/node_modules/telegraf/core/network/client.js:281:17

**Comment by Bitcoinera** [comment]
Mmm, weird, I cannot reproduce

**Comment by Bitcoinera** [comment]
Seems like you fixed it?

**Comment by jamiemadrox779** [comment]
Yes, fixed
