### ISSUE TITLE
Transfer transactions not being stored in DB

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/FastBTC#27]
Not even the confirmed transactions are being stored. This is what is causing all the `nulls` like in #25 

Investigating

**Comment by Bitcoinera** [comment]
Ah, I see the problem. It is because we were always using the test, `test_rskCtrl.js`. But there we never store the tx into the DB (`dbCtrl.addTransferTx`)

**Comment by Bitcoinera** [comment]
OK, will try this now, but maybe we can just close this one

**Comment by Bitcoinera** [comment]
OK, I think this one was because I was sending funds to the btcNode instead of the multisig. @jamiemadrox779 , can you confirm?

**Comment by jamiemadrox779** [comment]
Seems like, tx are all in db
