### ISSUE TITLE
txId or txHash for DepositTx

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/FastBTC#29]
In the function addDeposit, L167, we see it gets this parameters:
`async addDeposit(userAdrLabel, txHash, valueBtc, isConfirmed = false)`

But then, in bitcoinCtrl.js, L144, we see we are passing txId instead of txHash. This seems an important inconsistency

**Comment by Bitcoinera** [comment]
@jamiemadrox779  I think this is a bug, am I right?

https://github.com/DistributedCollective/FastBTC/blob/development/controller/bitcoinCtrl.js#L142
https://github.com/DistributedCollective/FastBTC/blob/development/controller/dbCtrl.js#L156

It should send txHash to the function, not txId? Or both?

**Comment by jamiemadrox779** [comment]
> In the function addDeposit, L167, we see it gets this parameters:
> `async addDeposit(userAdrLabel, txHash, valueBtc, isConfirmed = false)`
> 
> But then, in bitcoinCtrl.js, L144, we see we are passing txId instead of txHash. This seems an important inconsistency

Only the wording is different, the passed values are correct
txId passed by the btc node is the txhash

we used the same variable txId for our txId on rsk, to avoid confusion we should rename it to txIdRsk

**Comment by Bitcoinera** [comment]
> we used the same variable txId for our txId on rsk, to avoid confusion we should rename it to txIdRsk

I find txHash to be confusing, especially having the txIds from the smart contract. Why not txHashRsk?

**Comment by jamiemadrox779** [comment]
yes

**Comment by Bitcoinera** [comment]
OK, now I understand better what you meant. I think txId is in any case confusing, since we are more used to the term txHash. But I can also rename to txIdRsk the ones from transfer
