### ISSUE TITLE
Deposits not being detected

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/FastBTC#30]
The deposits I am sending to the BTC node 2MwUck... are not being processed. Did we change the node address somehow?

**Comment by jamiemadrox779** [comment]
This is not a node address but generated from the btc multisig

**Comment by Bitcoinera** [comment]
OK, so I was sending it to the wrong place then :sweat_smile:  Good bye, my test money :wave: 

Closing this then
