### ISSUE TITLE
Handle the case of multiple deposits on the same address within 1 transaction

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/FastBTC#46]
Example: 
address: 3MBcfjrGq35oszgfm9Z5G7EPxqdc5eE65S
tx: https://www.blockchain.com/btc/tx/97186b362e4cfa83e8a2f08beb76905ab6a05dffd942e40631c191497b97de3c

**Comment by ztane** [comment]
Easy to reproduce with Electrum actually, just use Tools=>Pay to many, enter the same address twice:

```
<depositaddress>,0.5
<depositaddress>,0.5
```

will generate two 0.5 mBTC deposits in the same transaction.

**Comment by ztane** [comment]
The complication is that the txhash, label is unique - actually it should be txhash, vout number.

**Comment by ztane** [comment]
Should be solved by https://github.com/DistributedCollective/FastBTC/pull/66
