### ISSUE TITLE
Add multiple Btc nodes to decrease deposit detection time

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/FastBTC#53]
With increasing users the deposit detection time increases because every address need to queeried.
Add the option to add add multiple nodes and then split the requests across these nodes.
Consider that the Btc nodes need to have the user label added first.

**Comment by ztane** [comment]
https://github.com/DistributedCollective/FastBTC/pull/58 could work as an alternative approach.

**Comment by jamiemadrox779** [comment]
Perfectly solved
