### ISSUE TITLE
Preserve users deposit history when migrating to a new multisig

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/FastBTC#61]
The new multisig will have segwit address format bc1....
Proposal: On getDepositAddress we check if the address on the db starts with bc1. If not -> we create a new address and overwrite the one in the db.
Please think about possible downsides.

**Comment by ztane** [comment]
I'd want to have more stuff in the db, for posterity if users want to issue more addresses. In the schema each user should have a *list* of addresses, all with the user's label + perhaps the current address that is shown as the preferred store address.

**Comment by jamiemadrox779** [comment]
Yes, but please create a new issues for this

**Comment by ztane** [comment]
This should be retained - the deposit history should be still available even with force-created bc1.
